import re
import json

class VibeTranslator:
    """
    The Vibe Core Translator: 
    Translates .vibe files into executable code for multiple platforms.
    """
    def __init__(self):
        self.version = "1.0.0-Alpha"
        self.platform_targets = ["python", "javascript", "cpp"]

    def parse_line(self, line):
        line = line.strip()
        if not line or line.startswith("#"):
            return None

        # 1. Goal Extraction
        if line.lower().startswith("goal:"):
            return {"type": "GOAL", "value": line.split(":", 1)[1].strip()}

        # 2. Strict Logic (!) - The Force
        if line.startswith("!"):
            return {"type": "STRICT", "value": line[1:].strip()}

        # 3. Creative Compilation (~) - The Vibe
        if line.startswith("~"):
            return {"type": "CREATIVE", "value": line[1:].strip()}

        # 4. Action Operator (>)
        if ">" in line:
            return {"type": "ACTION", "value": line.split(">", 1)[1].strip()}

        # 5. Iterative Intent (Human-Native Loops)
        if "repeat" in line.lower() and "times" in line.lower():
            count = re.findall(r'\d+', line)
            return {"type": "LOOP", "count": int(count[0]) if count else 1}

        return {"type": "NEUTRAL", "value": line}

    def generate_python(self, intents):
        code = ["# Generated by Vibe Core\nimport time\n"]
        indent = ""
        
        for item in intents:
            if not item: continue
            
            if item['type'] == 'STRICT':
                code.append(f"{indent}# Strict Logic: {item['value']}")
                # Simple mapping for 'Set X to Y'
                if "set" in item['value'].lower() and "to" in item['value'].lower():
                    parts = re.split('set|to', item['value'], flags=re.IGNORECASE)
                    code.append(f"{indent}{parts[1].strip()} = {parts[2].strip()}")
            
            elif item['type'] == 'LOOP':
                code.append(f"{indent}for _ in range({item['count']}):")
                indent = "    "
            
            elif item['type'] == 'ACTION':
                # Mapping 'print' or 'notify' to Python print
                action = item['value'].lower()
                if "print" in action or "notify" in action:
                    content = re.findall(r'\"(.+?)\"', action)
                    val = f'"{content[0]}"' if content else "item"
                    code.append(f"{indent}print({val})")
                elif "wait" in action:
                    code.append(f"{indent}time.sleep(1)")

        return "\n".join(code)

    def translate(self, vibe_script):
        print(f"🌊 Vibe Engine v{self.version} Starting...")
        lines = vibe_script.split('\n')
        intents = [self.parse_line(l) for l in lines]
        
        # In a real scenario, this would branch to different agents
        py_output = self.generate_python(intents)
        
        return py_output

# --- Implementation Example ---
if __name__ == "__main__":
    # Your Vibe Code
    my_script = """
    Goal: Simple Greeter
    ! Set Message to "Vibe is Live"
    Repeat 3 times:
        > print(Message)
        > wait 1 second
    ~ Style: Neon Blue interface
    """

    translator = VibeTranslator()
    python_code = translator.translate(my_script)

    print("\n--- TRANSLATED PYTHON CODE ---")
    print(python_code)
    print("------------------------------")
    
    # Save to file
    with open("output.py", "w") as f:
        f.write(python_code)
        print("✅ Saved to output.py")
